version: "3.3"
services:
    db:
        image: postgres:13.3
        environment:
            - POSTGRES_DB=app
            - POSTGRES_PASSWORD=12345678
        container_name: db
        ports:
            - "5432:5432"
        volumes:
            - ./db-data:/var/lib/postgresql/data/
    backend:
        build: ./flask-rest-api/
        container_name: backend
        ports:
            - "5000:5000"
    # frontend:
    #     build: ./react-frontend/
    #     container_name: frontend
    #     ports:
    #         - "3000:3000"
